# Generated by Django 4.0.4 on 2022-04-18 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automarket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='status',
            field=models.CharField(choices=[('E', 'Expected'), ('A', 'Available'), ('B', 'Booked'), ('S', 'Sold')], default='A', max_length=1),
            preserve_default=False,
        ),
    ]
